spring:
  profile:
    active: development

---

spring:
    profiles: default,development
server:
    port: 9060
recruit:
    message: Hello this is Dev machine!!

---

spring:
    profiles: production
server:
    port: 8080
recruit:
    message: Hello this is Prod machine!!
